config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations'
             }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'posts#index'

  resources :users, only: %i[index show]
  resources :posts, only: %i[new create index]
  resources :friend_requests, only: %i[index create destroy]
  resources :notifications, only: %i[index]
  resources :comments, only: %i[new create]
  resources :likes, only: %i[create]
  resources :profiles, only: %i[show edit update]
  resources :friends, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :person_films
  has_many :people, through: :person_films
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :notification

  def accept
    Friendship.create!(user: sender, friend: receiver)
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend,
             class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  has_one :friend_request, dependent: :destroy
  belongs_to :user
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :species
  belongs_to :home_planet, class_name: 'Planet'

  has_many :person_films
  has_many :films, through: :person_films
  
  has_one :senator, through: :home_planet
  has_many :neighbours, through: :home_planet, source: :citizens
end

app/models/person_film.rb
class PersonFilm < ApplicationRecord
  belongs_to :person
  belongs_to :film
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :senator, class_name: 'Person'
  has_many :citizens, class_name: 'Person', foreign_key: :home_planet_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :author, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/species.rb
class Species < ApplicationRecord
  has_many :people
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships,
           lambda { |user|
             unscope(where: :user_id)
               .where(user_id: user.id)
               .or(Friendship.where(friend_id: user.id))
           }

  has_many :friends,
           lambda { |user|
             # Don't get Users with the user's id (can't be friends with yourself)
             # Add Friendship.user_id to the join condition so we also
             # get any Users that added us as a friend
             where.not(id: user.id)
                  .joins('OR users.id = friendships.user_id')
           },
           through: :friendships

  has_many :friend_requests_as_sender,
           class_name: 'FriendRequest',
           foreign_key: :sender_id

  has_many :friend_requests_as_receiver,
           class_name: 'FriendRequest',
           foreign_key: :receiver_id

  has_many :posts, foreign_key: :author_id
  has_one :profile
  has_many :notifications
  has_many :comments

  has_many :likes
  has_many :hearts, class_name: 'Like'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def send_friend_request(to:)
    notification = send_notification(to:)
    friend_requests_as_sender.create!(receiver: to, notification:)
  end

  def sent_friend_request_to?(user)
    friend_requests_as_sender.where(receiver: user).count.positive?
  end

  def received_friend_request_from?(user)
    friend_requests_as_receiver.where(sender: user).count.positive?
  end

  def friends_with?(user)
    friends.where(id: user).count.positive?
  end

  def profile_photo
    email_address = email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    "https://www.gravatar.com/avatar/#{hash}"
  end

  def create_new_profile
    create_profile!(name: email.split('@').first)
  end

  private

  def send_notification(to:)
    Notification.create!(user: to)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc).select do |post|
      authored_by_current_user_or_friend?(post)
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content, :author_id)
  end

  def authored_by_current_user_or_friend?(post)
    post.author.eql?(current_user) ||
      current_user.friends_with?(post.author)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <% if false %>
    <div>
      <%= form.label :author_id, style: "display: block" %>
      <%= form.text_field :author_id %>
    </div>
  <% end %>

  <%= form.hidden_field(:author_id, value: current_user.id) %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <div><%= post.content %></div>
    <div><%= post.author.email %></div>
    <div><%= post.author.profile.name %></div>
    <div><strong><%= post.created_at %></strong></div>

    <div><%= link_to 'Add Comment', 
              new_comment_path(comment: { post_id: post.id }) %>
    </div>
    <h3>Comments</h3>
    <% post.comments.each do |comment| %>
      <div><%= comment.content %></div>
      <div>by: <%= comment.user.email %></div>
      <div><%= comment.created_at %></div>
      <br>
    <% end %>

    <div><%= button_to 'Like', 
              likes_path(like: { post_id: post, user_id: current_user }) %>
    </div>

    <h3>Likes</h3>
    <% post.likes.each do |like| %>
      <div>Liked by: <%= like.user.email %></div>
      <div><%= like.created_at %></div>
      <br>
    <% end %>
  </p>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<%= link_to "New post", new_post_path %>
<hr>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <hr>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>